App.init = async () => {
  let win = await App.browser().windows.getCurrent({populate: false})

  App.window_id = win.id
  App.manifest = App.browser().runtime.getManifest()
  App.header_url = App.browser().runtime.getURL(`header/index.html`)
  App.extension_id = App.browser().runtime.id
  App.browser_protocol = App.get_browser_protocol()

  App.print_intro()
  App.build_settings()

  await App.stor_compat_check()
  await App.stor_get_settings()
  await App.stor_get_command_history()
  await App.stor_get_tag_history()
  await App.stor_get_title_history()
  await App.stor_get_icon_history()
  await App.stor_get_first_time()
  await App.stor_get_notes()
  await App.stor_get_bookmark_folder_picks()
  await App.stor_get_history_picks()
  await App.stor_get_palette_history()
  await App.stor_get_datastore()
  await App.stor_get_memory()
  await App.stor_get_ai()
  await App.check_init_mode()

  App.make_tab_box_modes()
  App.setup_memory()
  App.setup_commands()
  App.setup_tabs()
  App.setup_closed()
  App.setup_settings()
  App.setup_tab_box()
  App.setup_active_trace()
  App.setup_tab_count()
  App.setup_keyboard()
  App.setup_window()
  App.setup_gestures()
  App.setup_filter()
  App.setup_modes()
  App.setup_scroll()
  App.setup_items()
  App.setup_theme()
  App.setup_drag()
  App.setup_favorites()
  App.setup_playing()
  App.setup_messages()
  App.setup_mouse()
  App.do_apply_theme()
  App.setup_pinline()
  App.setup_footer()
  App.setup_recent_tabs()
  App.setup_context()
  App.build_shell()
  App.mouse_inside_check()
  App.resolve_icons()

  await App.check_boosted()
  await App.clear_show()

  App.init_tab_box()
  App.make_window_visible()
  App.check_first_time()
  App.start_clock()
  App.start_main_title()
  await App.check_init_commands()
  App.start_signal_intervals()
  App.start_idle_tabs_check()
  App.start_progressive_fill()
  App.start_auto_color()
  App.start_themed_week()
  App.check_init_settings()
  await App.check_init_command()

  App.start_date = App.now()
}

App.init()