#!/usr/bin/env ruby
files = Dir.glob(File.join("js/main", '*'))
files.append("main.html")
files.append("css/style.css")
files.each do |file|
  content = File.read(file)
  fixed = content.gsub(/\n\s*\n\s*\n/, "\n\n")
  if content != fixed
    File.write(file, fixed)
    puts "Fixed: #{file}"
  end
end