#!/usr/bin/env ruby
require "json"
file = File.read("manifest.json")
manifest = JSON.parse(file)
version = manifest["version"]
zip_name = "grasshopper_v#{version}.zip"
`zip #{zip_name} -x \*.zip -r \*`
puts "Created #{zip_name}"