#!/usr/bin/env ruby
require "json"
file = File.read("manifest.json")
manifest = JSON.parse(file)
version = manifest["version"]
name = manifest["name"].downcase.split.join("_")
zip_name = "#{name}_v#{version}.zip"
`zip #{zip_name} -x \*.zip -r \*`
puts "Created #{zip_name}"